export const categories = [
	{
		id: "plant-based-foods-and-beverages",
		name: "Plant-based foods and beverages",
	},
	{ id: "plant-based-foods", name: "Plant-based foods" },
	{ id: "beverages", name: "Beverages" },
	{ id: "snacks", name: "Snacks" },
	{ id: "breakfasts", name: "Breakfasts" },
	{ id: "dairies", name: "Dairies" },
	{ id: "desserts", name: "Desserts" },
	{ id: "meats", name: "Meats" },
	{ id: "cereals", name: "Cereals" },
	{ id: "pizzas", name: "Pizzas" },
	{ id: "biscuits", name: "Biscuits" },
	{ id: "cheeses", name: "Cheeses" },
	{ id: "juices", name: "Juices" },
	{ id: "sodas", name: "Sodas" },
	{ id: "yogurts", name: "Yogurts" },
	{ id: "breads", name: "Breads" },
	{ id: "pastries", name: "Pastries" },
	{ id: "chocolates", name: "Chocolates" },
	{ id: "salads", name: "Salads" },
	{ id: "prepared-meals", name: "Prepared meals" },
	{ id: "fruit-based-beverages", name: "Fruit-based beverages" },
	{ id: "milk", name: "Milk" },
	{ id: "teas", name: "Teas" },
	{ id: "coffees", name: "Coffees" },
	{ id: "sausages", name: "Sausages" },
	{ id: "sauces", name: "Sauces" },
	{ id: "soups", name: "Soups" },
	{ id: "energy-drinks", name: "Energy drinks" },
	{ id: "ice-creams", name: "Ice creams" },
	{ id: "oils", name: "Oils" },
	{ id: "spreads", name: "Spreads" },
	{ id: "baby-foods", name: "Baby foods" },
	{ id: "legumes", name: "Legumes" },
	{ id: "rice", name: "Rice" },
	{ id: "pasta", name: "Pasta" },
	{ id: "jams", name: "Jams" },
	{ id: "honey", name: "Honey" },
	{ id: "margarines", name: "Margarines" },
	{ id: "seasonings", name: "Seasonings" },
	{ id: "seafood", name: "Seafood" },
	{ id: "sweetened-beverages", name: "Sweetened beverages" },
	{ id: "flavored-yogurts", name: "Flavored yogurts" },
	{ id: "breakfast-cereals", name: "Breakfast cereals" },
	{ id: "energy-bars", name: "Energy bars" },
	{ id: "muffins", name: "Muffins" },
];
